import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto flex w-full max-w-[102ch] flex-col antialiased`}
      >
        {children}
        <footer className="mt-24 py-6 border-t text-center text-sm text-gray-500 dark:text-gray-400 dark:border-gray-700">
          <p>
            © {new Date().getFullYear()} Spam Detector Project • Built by Nitesh
            Pradhan
          </p>
        </footer>
      </body>
    </html>
  );
}
